server:
  port: 6003

spring:
  application:
    name: center-auth

  cloud:
    nacos:
      discovery:
        server-addr: 1.117.117.104:8848
  redis:
    database: 0
    port: 6379
    host: localhost
    password:


# 用于actuator暴露监控指标
management:
  endpoints:
    web:
      exposure:
        include: "*"