server:
  port: 6001

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 1.117.117.104:8848
    gateway:
      routes:
        - id: test
          uri: lb://center-test  # 后端服务名
          predicates:
            - Path=/test/**   # 路由地址
          filters:
            - StripPrefix=1 # 去掉前缀


# 用于actuator暴露监控指标
management:
  endpoints:
    web:
      exposure:
        include: "*"